version: '3.7'
services:
  app:
    build:
      dockerfile: ./Dockerfile 

    depends_on:
      - db 

    
    

  db:
    image: postgres 
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"